name: quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  typecheck:
    name: typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --dev --frozen

      - name: Run typecheck
        run: make typecheck

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --dev --frozen

      - name: Run linter
        run: make lint
